@url=http://api-hml.rastreei.com/api

GET {{url}}/localizacao
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vd3d3LnJhc3RyZWVpLmNvbSIsImF1ZCI6Im5vZGVqcy1qd3QtYXV0aCIsImV4cCI6MTU3ODYyNTUzOSwic2NvcGUiOiJmdWxsX2FjY2VzcyIsImRhdGEiOnsiaWRfdXN1YXJpbyI6MSwiaWRfdGlwb191c3VhcmlvIjowLCJub21lIjoiUkFTVFJFRUkiLCJpZF91c3VhcmlvX2xvZ2luIjoyMjM0LCJub21lX2xvZ2luIjoiUkFTVFJFRUkgQVBJIiwiZW1haWwiOiJjb250YXRvQHJhc3RyZWVpLmNvbSIsImlkX3BlcmZpbF9sb2dpbiI6NSwiaWRfc3RhdHVzIjoxLCJmbGdfdXBkYXRlX3Bhc3N3b3JkIjoxfSwianRpIjoiZ0pRSk9DTkZMdGR3TVBubCIsImFsZyI6IkhTMjU2IiwiaWF0IjoxNTc4MDIwNzM5fQ.BdoayELJ4dNdqkipheux5giq-NfBh31KQeMxO2g-dzY
